all: main
main: main.o sudoku.o
	g++ -Wall -std=c++11 -o main main.o sudoku.o

main.o: main.cpp
	g++ -std=c++11 -c -Wall main.cpp

sudoku.o: sudoku.cpp
	g++ -std=c++11 -c -Wall sudoku.cpp

clean:
	del *o
